metadata.format.version = "1.1"

[versions]

minecraft = "1.21.10"
loader = "0.17.3"
api = "0.135.0" #Dont include the minecraft version
brigadier = "1.2.9"
parchment_mappings="2025.10.12"
neo="21.9.16-beta"
neoform="20251010.172816" #Dont include the minecraft version
mixin="0.8.5"
extras="0.5.0"
velocity="3.4.0-SNAPSHOT"

authlib="7.0.61"
h2="2.3.232"
gson="2.10.1"
mysql="8.0.33"
mariadb="3.3.2"

shadow-gradle-plugin="9.1.0"
paperweight-userdev="2.0.0-beta.18"
moddev-gradle="2.0.115"
fabric-loom="1.11-SNAPSHOT"
minotaur="2.8.10"
curseforge="1.1.26"
hangar="0.1.3"
github-release="2.5.2"

[libraries]
# Project General
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "api" }
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
extras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "extras" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }

# Always Auth Specific
authlib = { module = "com.mojang:authlib", version.ref = "authlib" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
mysql = { module = "mysql:mysql-connector-java", version.ref = "mysql" }
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# Build Stuff
shadow-gradle-plugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow-gradle-plugin" }
paperweight-userdev = { module = "io.papermc.paperweight:paperweight-userdev", version.ref = "paperweight-userdev" }
moddev-gradle = { module = "net.neoforged:moddev-gradle", version.ref = "moddev-gradle" }
fabric-loom = { module = "fabric-loom:fabric-loom.gradle.plugin", version.ref = "fabric-loom" }
minotaur = { module = "com.modrinth.minotaur:Minotaur", version.ref = "minotaur" }
curseforge = { module = "net.darkhax.curseforgegradle:net.darkhax.curseforgegradle.gradle.plugin", version.ref = "curseforge" }
hangar = { module = "io.papermc.hangar-publish-plugin:io.papermc.hangar-publish-plugin.gradle.plugin", version.ref = "hangar" }
github-release = { module = "com.github.breadmoirai:github-release", version.ref = "github-release" }

[bundles]
build = [
    "shadow-gradle-plugin",
    "paperweight-userdev",
    "moddev-gradle",
    "fabric-loom",
    "minotaur",
    "curseforge",
    "hangar",
    "github-release"
]