metadata.format.version = "1.1"

[versions]

minecraft = "1.21.10"
loader = "0.17.3"
api = "0.135.0" #Dont include the minecraft version
brigadier = "1.2.9"
parchment_mappings="2025.10.12"
neo="21.9.16-beta"
neoform="20251010.172816" #Dont include the minecraft version
mixin="0.8.5"
extras="0.5.0"
velocity="3.4.0-SNAPSHOT"

authlib="7.0.61"
h2="2.3.232"
gson="2.10.1"
mysql="8.0.33"
mariadb="3.3.2"

shadow-gradle-plugin="9.1.0"
paperweight-userdev="2.0.0-beta.18"
moddev-gradle="2.0.115"
fabric-loom="1.11-SNAPSHOT"
minotaur="2.8.10"
curseforge="1.1.26"
hangar="0.1.3"

[libraries]
# Project General
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "loader" }
fabric_api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "api" }
brigadier = { group = "com.mojang", name = "brigadier", version.ref = "brigadier" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
extras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "extras" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

# Always Auth Specific
authlib = { group = "com.mojang", name = "authlib", version.ref = "authlib" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
mysql = { group = "mysql", name = "mysql-connector-java", version.ref = "mysql" }
mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "mariadb" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Build Stuff
shadow-gradle-plugin = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow-gradle-plugin" }
paperweight-userdev = { group = "io.papermc.paperweight", name = "paperweight-userdev", version.ref = "paperweight-userdev" }
moddev-gradle = { group = "net.neoforged", name = "moddev-gradle", version.ref = "moddev-gradle" }
fabric-loom = { group = "fabric-loom", name = "fabric-loom.gradle.plugin", version.ref = "fabric-loom" }
minotaur = { group = "com.modrinth.minotaur", name = "Minotaur", version.ref = "minotaur" }
curseforge = { group = "net.darkhax.curseforgegradle", name = "net.darkhax.curseforgegradle.gradle.plugin", version.ref = "curseforge" }
hangar = { group = "io.papermc.hangar-publish-plugin", name = "io.papermc.hangar-publish-plugin.gradle.plugin", version.ref = "hangar" }

[bundles]
build = [
    "shadow-gradle-plugin",
    "paperweight-userdev",
    "moddev-gradle",
    "fabric-loom",
    "minotaur",
    "curseforge",
    "hangar"
]